### ISSUE TITLE
关于dapp，我运行了程序，dapp无法连接我的钱包

### ISSUE THREAD

**Issue by wkn66** [JianBinWu/Wallet-iOS#2]
我运行起来程序，点击dapp跳转后，无法连接钱包，我选择了eth地址也是无法连接。不知道你是怎么操作的，请给个运行示例，非常感谢

**Comment by JianBinWu** [comment]
麻烦pull下代码，重新测试下。。

**Comment by JianBinWu** [comment]
> 我运行起来程序，点击dapp跳转后，无法连接钱包，我选择了eth地址也是无法连接。不知道你是怎么操作的，请给个运行示例，非常感谢

麻烦pull下代码，重新测试下。。

**Comment by wkn66** [comment]
嗨朋友，我重新pull了下 点击dapp进去，还是没能链接walllet钱包内的地址啊。如果方便的话，您加我下微信：whysoledad

**Comment by JianBinWu** [comment]
> 嗨朋友，我重新pull了下 点击dapp进去，还是没能链接walllet钱包内的地址啊。如果方便的话，您加我下微信：whysoledad

点击打开DApp后，点击按钮Connect Wallet，再选第一个WalletConnect，在钱包列表里随便选一个钱包便可以连接（例如选imToken）

**Comment by wkn66** [comment]
我的意思是  能不能连接demo里的wallet，进入demo后不是已经创建好了eth钱包么，我点击dapp进入浏览器 是不是应该默认连接钱包内已经创建好的eth地址

**Comment by JianBinWu** [comment]
> 我的意思是 能不能连接demo里的wallet，进入demo后不是已经创建好了eth钱包么，我点击dapp进入浏览器 是不是应该默认连接钱包内已经创建好的eth地址

自动连接需要浏览器注入JS代码，相关代码不方便透露。使用WalletConnect协议连接方案的话，就需要手动点击连接

**Comment by wkn66** [comment]
好的  明白了  谢谢帮助
